name: "publish"

on:
  push:
    tags:
      - "v*.*.*" # This matches all tags with a version number format like v1.0.0

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod Download
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Build
        run: |
          templ generate
          go build -o main ./cmd/...

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "main"
          body: "Automated release based on tag ${{ github.ref_name }}."
          draft: false
          prerelease: false
